# .github/release.yml

changelog:
  exclude:
    labels:
      - "skip-changelog"
      - "dependencies"
  categories:
    - title: "🚀 Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "fix"
        - "bug"
    - title: "📄 Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "🔨 Maintenance"
      labels:
        - "chore"
        - "refactor"
        - "test"
        - "ci"
    - title: "Other Changes"
      labels:
        - "*"
